### ISSUE TITLE
关于 《接口响应体格式统一封装》这篇文章, 出现了中文乱码

### ISSUE THREAD

**Issue by youngxinler** [zhumaer/zhuma#1]
首先, 感谢井哥,  让我知道了在spring boot上面这么多优雅解决问题的方式.
我的spring boot版本是2.1.4
我是通过InterceptorConfig继承WebMvcConfigurationSupport解决的, 不知道是不是最佳的方式.
还请井哥如果有时间的话可以指教一下.^_^
(WebMvcConfigurerAdapter在新版本中已经废弃, 所以我继承了WebMvcConfigurationSupport)
`
    @Bean
    public HttpMessageConverter<String> responseBodyConverter(){
        return new StringHttpMessageConverter(Charset.forName("UTF-8"));
    }

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converterList){
        converterList.add(responseBodyConverter());
        addDefaultHttpMessageConverters(converterList);
    }
`

**Comment by willxiang** [comment]
你试试实现WebMvcConfigurer
